### ISSUE TITLE
Wireflow/design

### ISSUE THREAD

**Issue by KoenHaagsma** [KoenHaagsma/ProjectTechKSA#9]

**Comment by AllyssaA** [comment]
Started working on a wireflow and design.

Check it out https://www.figma.com/file/3CtVYDGpY4ZlMuWozpsHBA/TeamKSA?node-id=0%3A1

**Comment by KoenHaagsma** [comment]
Looks great @AllyssaA

**Comment by judithkoelewijn** [comment]
Created a new design / visual style. Started with the login screen for some feedback. Maybe we can combine it with the following SVG images. Some thoughts? https://xd.adobe.com/view/87f111f1-fe6e-4d0e-ae48-52f6659f4064-d2a2/
I like @AllyssaA her layout and think the userflow is great, but I think we might improve the design a little, but let me know, it's just visually not layout.

**Comment by KoenHaagsma** [comment]
@judithkoelewijn I think we can continue with your style it has some combinations with @AllyssaA we will discuss later today.

**Comment by judithkoelewijn** [comment]
https://xd.adobe.com/view/87f111f1-fe6e-4d0e-ae48-52f6659f4064-d2a2/ New design with more screens
